### ISSUE TITLE
pytemplate: add `pyupgrade` hook

### ISSUE THREAD

**Issue by ernieIzde8ski** [ernieIzde8ski/cc-templates#11]
would be nice: <https://github.com/asottile/pyupgrade>

example usage:

```yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: ""
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
```
