### ISSUE TITLE
pytemplate: Switch to `ruff` formatter

### ISSUE THREAD

**Issue by ernieIzde8ski** [ernieIzde8ski/cc-templates#5]
I like it

```toml
[tool.ruff]
line-length       = 90
indent-width    = 4
target-version  = "py310"

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true
```
